### ISSUE TITLE
No module named 'lib.keyboard_helper'

### ISSUE THREAD

**Issue by kcrazy** [GrahamMThomas/MapleAITrainer#1]
Hello:
It seems that some packages are missing in the repository, 
such as 'lib' and 'train_and_log_callback'.

**Comment by GrahamMThomas** [comment]
That is super weird... I have no idea how it was dropped. I'll try to find it today

**Comment by GrahamMThomas** [comment]
I moved them into a lib folder. But `lib` was in my autogenerated gitignore so they ended up getting dropped. I pulled them out of the githistory and put them into a lib folder. 

Thanks for the catch.
